### ISSUE TITLE
Request Fiture Oauth2

### ISSUE THREAD

**Issue by Jayuda** [xcv58/meteor-collectionapi#19]
Hello, 
Thanks for this add on. 
Can we implement Oauth2 for authorisation?

**Comment by xcv58** [comment]
You can use the [oauth2 packge](https://atmospherejs.com/meteor/oauth2) and the authenticate function https://github.com/xcv58/meteor-collectionapi#custom-authenticate-function together.

I don't have any plan to add Oauth2 inside this package. Because someone may need custom permission and user role. It's flexible to use authenticate callback to delegate the auth process to other parts.

**Comment by Jayuda** [comment]
Ok Thanks
